### PR TITLE
Changed nested ifelses to recode

### PR DESCRIPTION
**Pull request by chrmongeau**
Instead of using nested ifelses (as a switch case), use recode() in order to make the code more readable.

### CODE REVIEW

**Comment by chrmongeau** [comment]
I'll leave this pull request unmerged for a while (as it's not critical) so that if a caveat of using `recode` of which I'm not aware of is found (e.g., `recode` was added in dplyr 0.5.0 and I don't know if we need to do a package version check).

**Comment by sebastian-c** [comment]
`dplyr 0.5.0` is not currently installed on the server. If you'd like it to be, send me an email.

**Comment by chrmongeau** [comment]
Done. Thanks.

**Comment by sebastian-c** [comment]
It has since been installed.

**Pull request merged**
